---
title: "Deeper analysis of the influence of confounding factors"
author: "Aram Safrastyan"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: 
    toc: TRUE
    code_folding: hide
    number_sections: TRUE
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = "./html_output"
    )
  })
editor_options: 
  chunk_output_type: console
---

<style type="text/css">
.main-container {
  max-width: 1500px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r pkgs, message=F, warning=F}
library(tidyverse)
library(ggpubr)
library(patchwork)
library(ggpubr)
library(rstatix)
library(glmnet)
library(plotROC)
library(pROC)
```

```{r setup, include=FALSE}
theme_set(theme_classic(base_size = 18))
```

# Influence of donor/patient age on classification results per gender

```{r age, fig.width= 15, fig.height=8, warning = FALSE}
# load("./data/cfdata_input.RData")
# load("/home/bioinf/Desktop/cfdeconv_manuscript/cfdeconv/data/cfinput_clean_filt.RData")
# elife_meta <- read.csv("~/R_main/cfdeconv_model/cfdata/metadata/elife_meta.txt") %>% dplyr::filter(disease %in% c("Healthy donor", "Liver Cancer patient")) %>% dplyr::mutate(cond = as.factor(ifelse(disease=="Liver Cancer patient", "LC", "HD")))
# df <- data.frame(age = c(npj_meta_filt$Age.x, elife_meta$Age, therano_meta$age, frontiers_meta_filt$Age.y), gender = c(npj_meta_filt$gender, elife_meta$gender, therano_meta$gender, frontiers_meta_filt$Gender), cond = c(npj_meta_filt$cond, elife_meta$cond, therano_meta$cond, frontiers_meta_filt$cond)) %>% dplyr::mutate(age = as.numeric(ifelse(age=="missing", "", age))) %>% dplyr::mutate(gender = ifelse(gender=="M", "male", gender)) %>% dplyr::mutate(gender = ifelse(gender=="F", "female", gender)) %>% na.omit()
# p2 <- df %>% ggplot(., aes(x=gender, y=age, color = gender)) + geom_violin(trim=F) + geom_dotplot(binaxis='y', stackdir='center', dotsize=1) + xlab(element_blank()) + facet_wrap(~cond) + ggpubr::theme_pubclean(base_family = "Helvetica", base_size = 16)
# p2
# ggarrange(p2, p1, nrow = 2, labels = "AUTO", font.label = list(size = 18, family = "Helvetica"))

# load data
load("./temp_files/cfdeconv_res.RData")
load("./data/deconv_res_filt.RData")
therano_clean <- therano_meta_deconv_filt %>%
  dplyr::select(-c(1:7)) %>%
  dplyr::mutate(cond = factor(cond, levels = c("HD", "LC")))
npj_clean <- npj_meta_deconv_filt %>%
  dplyr::select(c(cond, 37:47)) %>%
  dplyr::mutate(cond = factor(cond, levels = c("HD", "LC")))

# therano
therano_pd <- cfdeconv_log %>% dplyr::filter(dataset == "Zhu et al. (2021)")
therano_meta_deconv_filt$pred <- as.numeric(therano_pd$pred_class)

# npj
npj_meta_deconv_filt$pred <- deconv_npj$pred_class

# construct a unified df
df <- data.frame(age = c(npj_meta_deconv_filt$Age.x, therano_meta_deconv_filt$age), gender = c(npj_meta_deconv_filt$gender, therano_meta_deconv_filt$gender), cond = c(npj_meta_deconv_filt$cond, therano_meta_deconv_filt$cond), pred = c(npj_meta_deconv_filt$pred, therano_meta_deconv_filt$pred)) %>% dplyr::mutate(pred = as.factor(ifelse(pred == 0, "HD", "LC")))

# choose misclassified samples
df1 <- df %>% dplyr::filter((cond == "HD" & pred == "LC") | (cond == "LC" & pred == "HD"))

# plot all samples
t1 <- df %>% ggplot(., aes(x = gender, y = age, color = gender)) +
  geom_violin(trim = F) +
  geom_dotplot(binaxis = "y", stackdir = "center", dotsize = 1) +
  scale_y_continuous(breaks = seq(20, 100, by = 20)) +
  xlab(element_blank()) +
  facet_wrap(~cond) +
  ggpubr::theme_pubclean(base_family = "Helvetica", base_size = 18)
t1

# plot only mislassified samples
t2 <- df %>%
  dplyr::filter((cond == "HD" & pred == "LC") | (cond == "LC" & pred == "HD")) %>%
  ggplot(., aes(x = gender, y = age, color = gender)) +
  geom_violin(trim = F) +
  geom_dotplot(binaxis = "y", stackdir = "center", dotsize = 1) +
  xlab(element_blank()) +
  facet_wrap(~cond) +
  ggpubr::theme_pubclean(base_family = "Helvetica", base_size = 18)
t2

# arrange plots
p1 <- ggarrange(t1, t2, nrow = 2, labels = "AUTO", font.label = list(size = 20, family = "Helvetica"), common.legend = T)

# export
ggsave(plot = p1, file = "./figures/suppl6.png", units = "mm", device = ragg::agg_png, height = 90, width = 170, scaling = 0.45, limitsize = FALSE, dpi = 300)

# stat tests
stat.test <- df %>%
  dplyr::group_by(gender) %>%
  wilcox_test(age ~ cond, alternative = "t", exact = TRUE, conf.level = 0.95, p.adjust.method = "BH", paired = FALSE)
stat.test_effect <- df %>%
  dplyr::group_by(gender) %>%
  wilcox_effsize(age ~ cond, alternative = "t", conf.level = 0.95, paired = FALSE, ci = TRUE, nboot = 100)
stat.test1 <- df1 %>%
  dplyr::group_by(gender) %>%
  wilcox_test(age ~ cond, alternative = "t", exact = TRUE, conf.level = 0.95, p.adjust.method = "BH", paired = FALSE)
stat.test_effect1 <- df1 %>%
  dplyr::group_by(gender) %>%
  wilcox_effsize(age ~ cond, alternative = "t", conf.level = 0.95, paired = FALSE, ci = TRUE, nboot = 100)

stat.test2 <- df %>%
  dplyr::group_by(cond) %>%
  wilcox_test(age ~ gender, alternative = "t", exact = TRUE, conf.level = 0.95, p.adjust.method = "BH", paired = FALSE)
stat.test_effect2 <- df %>%
  dplyr::group_by(cond) %>%
  wilcox_effsize(age ~ gender, alternative = "t", conf.level = 0.95, paired = FALSE, ci = TRUE, nboot = 100)
stat.test3 <- df1 %>%
  dplyr::group_by(cond) %>%
  wilcox_test(age ~ gender, alternative = "t", exact = TRUE, conf.level = 0.95, p.adjust.method = "BH", paired = FALSE)
stat.test_effect3 <- df1 %>%
  dplyr::group_by(cond) %>%
  wilcox_effsize(age ~ gender, alternative = "t", conf.level = 0.95, paired = FALSE, ci = TRUE, nboot = 100)

df$type <- "full"
df1$type <- "mis"
df3 <- rbind(df, df1)
stat.test4 <- df3 %>%
  dplyr::mutate(gender = factor(gender, levels = c("female", "male"))) %>% 
  dplyr::group_by(gender, cond) %>%
  wilcox_test(age ~ type, alternative = "t", exact = TRUE, conf.level = 0.95, p.adjust.method = "BH", paired = FALSE)
stat.test_effect4 <- df3 %>%
  dplyr::mutate(gender = factor(gender, levels = c("female", "male"))) %>% 
  dplyr::group_by(gender, cond) %>%
  wilcox_effsize(age ~ type, alternative = "t", conf.level = 0.95, paired = FALSE, ci = TRUE, nboot = 100)

save(stat.test, stat.test_effect, stat.test1, stat.test_effect1, stat.test2, stat.test_effect2, stat.test3, stat.test_effect3, stat.test4, stat.test_effect4, file = "./temp_files/age_stat.RData")
```

# Influence of sample collection date on classification results

```{r bleed, fig.width= 15, fig.height=8, warning = FALSE}
# load deconv results
load("./data/deconv_res_filt.RData")
# load the saved model
load("./temp_files/deconv_logmodel.RData")
# bleed dates
frontiers_meta_deconv_filt$bleed <- as.character(frontiers_meta_deconv_filt$bleed)
frontiers_meta_deconv_filt <- frontiers_meta_deconv_filt %>% dplyr::rename(bleed_date = bleed)
# partition and analysis of bleed dates
# all dates
frontiers_clean <- frontiers_meta_deconv_filt # %>% dplyr::filter(Tissue != "Plasma vesicles")
frontiers_meta_deconv_filt[frontiers_meta_deconv_filt$id == "HCC001M", "bleed_date"] <- frontiers_meta_deconv_filt[frontiers_meta_deconv_filt$id == "HCC001", "bleed_date"]
frontiers_meta_deconv_filt[frontiers_meta_deconv_filt$id == "HCC007M", "bleed_date"] <- frontiers_meta_deconv_filt[frontiers_meta_deconv_filt$id == "HCC007", "bleed_date"]
frontiers_meta_deconv_filt[frontiers_meta_deconv_filt$id == "HCC004M", "bleed_date"] <- frontiers_meta_deconv_filt[frontiers_meta_deconv_filt$id == "HCC004", "bleed_date"]
frontiers_meta_deconv_filt[frontiers_meta_deconv_filt$id == "HCC006M", "bleed_date"] <- frontiers_meta_deconv_filt[frontiers_meta_deconv_filt$id == "HCC006", "bleed_date"]
frontiers_meta_deconv_filt[frontiers_meta_deconv_filt$id == "HCC101M", "bleed_date"] <- frontiers_meta_deconv_filt[frontiers_meta_deconv_filt$id == "HCC101", "bleed_date"]


frontiers_clean_filt <- frontiers_meta_deconv_filt %>%
  # dplyr::filter(Tissue != "Plasma vesicles") %>%
  dplyr::select(-c(1:48)) %>%
  mutate(cond = factor(cond, levels = c("HD", "LC")))
# model performance
npj_frontiers_filt <- predict(elnet_npj, as.matrix(frontiers_clean_filt[, -which(names(frontiers_clean_filt) %in% c("cond"))]), type = "response")
pd_front_filt <- ifelse(npj_frontiers_filt[, 1] < best_thr$threshold, "0", "1")
frontiers_clean_filt$pred <- pd_front_filt
frontiers_clean_filt$prob <- npj_frontiers_filt[, 1]
# filter all samples with bleed date older than 2010
frontiers_clean_2010 <- frontiers_clean_filt %>% dplyr::filter(frontiers_clean$bleed_date > "2010-12-12" | is.na(frontiers_clean$bleed_date == "NA"))
roc_frontiers_2010 <- roc(as.numeric(frontiers_clean_2010$cond == "LC"), frontiers_clean_2010$prob, plot = TRUE, print.auc = TRUE, ci = TRUE, print.thres = TRUE, levels = c(0, 1), direction = "<", main = "npj-elife (elnet)")
# filter all samples with bleed daze older than 2016
frontiers_clean_2016 <- frontiers_clean_filt %>% dplyr::filter(frontiers_clean$bleed_date > "2016-12-12" | is.na(frontiers_clean$bleed_date == "NA"))
roc_frontiers_2016 <- roc(as.numeric(frontiers_clean_2016$cond == "LC"), frontiers_clean_2016$prob, plot = TRUE, print.auc = TRUE, ci = TRUE, print.thres = TRUE, levels = c(0, 1), direction = "<")
# aggregate results
all_roc <- data.frame(resp = as.factor(c(frontiers_clean_filt$cond, frontiers_clean_2010$cond, frontiers_clean_2016$cond)), pred = c(frontiers_clean_filt$prob, frontiers_clean_2010$prob, frontiers_clean_2016$prob), dataset = c(rep("full dataset", times = nrow(frontiers_clean_filt)), rep("bleed date > 12-12-2010", times = nrow(frontiers_clean_2010)), rep("bleed date > 12-12-2016", nrow(frontiers_clean_2016)))) %>%
  dplyr::mutate(resp = ifelse(resp == "LC", 1, 0)) %>%
  dplyr::mutate(dataset = factor(dataset, levels = c("full dataset", "bleed date > 12-12-2010", "bleed date > 12-12-2016")))

# plot results
a <- ggplot(all_roc, aes(d = resp, m = pred, color = dataset)) +
  geom_roc(n.cuts = 0) +
  style_roc() +
  geom_abline() +
  theme_pubr(base_size = 16, base_family = "Helvetica") +
  theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 18), plot.subtitle = element_text(hjust = 0.5, face = "bold"), plot.caption = element_text(size = 12, hjust = 1, vjust = 0, face = "italic", color = "black")) +
  guides(color = guide_legend(override.aes = list(linewidth = 10)))

b <- data.frame(dataset = calc_auc(a)$dataset, AUC = round((calc_auc(a))$AUC, 2)) %>%
  dplyr::mutate(dataset = factor(dataset, levels = c("full dataset", "bleed date > 12-12-2010", "bleed date > 12-12-2016"))) %>%
  dplyr::mutate(n_dataset = paste0("(", "n =", " ", table(all_roc$dataset), ")"))
in_plot <- ggplot(b, aes(x = dataset, y = AUC, fill = dataset)) +
  geom_col() +
  geom_text(data = b, aes(x = dataset, y = AUC + 0.15, label = n_dataset), color = "black", size = 4.65) +
  geom_text(aes(label = AUC), nudge_y = 0.05, color = "black", size = 4.65) +
  scale_x_discrete(labels = NULL, breaks = NULL) +
  labs(x = "") +
  ggtitle("AUC values of the ROC curves") +
  theme_pubclean(base_size = 13, base_family = "Helvetica") +
  theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 13.5), axis.text.x = element_blank(), axis.title.x = element_blank(), plot.caption = NULL) +
  guides(fill = "none")
p1 <- a + annotation_custom(
  ggplotGrob(in_plot),
  xmin = 0.55, xmax = 1.00, ymin = -0.07, ymax = 0.55
)
p1
ggsave(plot = p1, file = "./figures/suppl7.png", units = "mm", device = ragg::agg_png, height = 90, width = 170, scaling = 0.45, limitsize = FALSE, dpi = 300)
```

```{r}
sessionInfo()
```
